global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: 'app'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nobara:51234'] # This part may need to changed

# To sync data to Grafana Mimir
remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: 123456
      password: glc_XXXXXXXXXXXXXXXXXXXXXx
